import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { motion } from "framer-motion"
import { FaTwitter, FaGithub } from 'react-icons/fa'
import { SiZenn } from 'react-icons/si'

import { Archivo_Black } from 'next/font/google'

const archivoBlack = Archivo_Black({
  weight: '400',
  subsets: ['latin'],
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.home}>
        {/* Introduce */}
        <div className={`section ${styles.main}`}>
          <div>
            <motion.div {...headTextAnimation}>
              <h1 className={`${archivoBlack.className} ${styles.name}`}>
                Airi Narita
              </h1>
            </motion.div>
            <motion.div {...headContentAnimation}>
              <h2 className={styles.title}>
                Nothing impossible!!!
              </h2>
              <p className={styles.description}>
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptatum illum praesentium, corrupti tempora totam laudantium sit unde optio necessitatibus iusto repellendus quae magni nobis minima consectetur ab quam aliquid et!
              </p>
            </motion.div>
            <motion.div {...headContentAnimation} className={styles.sns}>
              <motion.div
                whileHover={{ scale: 1.1 }}
                whileTap={{ scale: 0.9 }}
                className={styles.snsItem}
              >
                <a href="https://twitter.com/aaaairinkiyowo" target='_blank'>
                  <FaTwitter size={'1.6rem'} />
                </a>
              </motion.div>
              <motion.div
                whileHover={{ scale: 1.1 }}
                whileTap={{ scale: 0.9 }}
                className={styles.snsItem}
              >
                <a href="https://github.com/airinarita" target='_blank'>
                  <FaGithub size={'1.6rem'}></FaGithub>
                </a>
              </motion.div>
              <motion.div
                whileHover={{ scale: 1.1 }}
                whileTap={{ scale: 0.9 }}
                className={styles.snsItem}
              >
                <a href="https://zenn.dev/airiswim" target='_blank'>
                  <SiZenn size={'1.6rem'} />
                </a>
              </motion.div>
            </motion.div>
          </div>
          <motion.div {...headImageAnimation}>
            <div className={styles.selfImage}>
              <img src="https://images.unsplash.com/photo-1682832847143-4696ff5dc87a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80" alt="ㅅㄷㄴㅅ" />
            </div>
          </motion.div>
        </div>
        {/* Slider */}
        <div className={`section ${styles.slider}`}>
          <div className={styles.sliderInner}>
            <div className={styles.sliderItem}>1</div>
            <div className={styles.sliderItem}>2</div>
            <div className={styles.sliderItem}>3</div>
            <div className={styles.sliderItem}>4</div>
            <div className={styles.sliderItem}>5</div>
            <div className={styles.sliderItem}>6</div>
            <div className={styles.sliderItem}>7</div>
            <div className={styles.sliderItem}>8</div>
          </div>
        </div>
        {/* Portfolio */}
        <div className={`section ${styles.portfolio}`}>
          <h2 className="sectionTitle">Portfolio</h2>
          <div className={styles.portfolioInner}>
            <div className={styles.portfolioCard}>
              <img className={styles.portfolioImage} src="https://images.unsplash.com/photo-1625842268584-8f3296236761?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80" alt="" />
              <div className={styles.portfolioContent}>
                <h4 className={styles.portfolioTitle}>Together</h4>
                <p className={styles.portfolioDescription}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti illo earum reprehenderit voluptatem nulla quae voluptates, blanditiis cum? Quidem praesentium, dolores velit animi quod cumque dignissimos sed sapiente at eius.</p>
              </div>
            </div>

            <div className={styles.portfolioCard}>
              <img className={styles.portfolioImage} src="https://images.unsplash.com/photo-1625842268584-8f3296236761?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80" alt="" />
              <div className={styles.portfolioContent}>
                <h4 className={styles.portfolioTitle}>Together</h4>
                <p className={styles.portfolioDescription}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti illo earum reprehenderit voluptatem nulla quae voluptates, blanditiis cum? Quidem praesentium, dolores velit animi quod cumque dignissimos sed sapiente at eius.</p>
              </div>
            </div>

            <div className={styles.portfolioCard}>
              <img className={styles.portfolioImage} src="https://images.unsplash.com/photo-1625842268584-8f3296236761?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80" alt="" />
              <div className={styles.portfolioContent}>
                <h4 className={styles.portfolioTitle}>Together</h4>
                <p className={styles.portfolioDescription}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti illo earum reprehenderit voluptatem nulla quae voluptates, blanditiis cum? Quidem praesentium, dolores velit animi quod cumque dignissimos sed sapiente at eius.</p>
              </div>
            </div>

            <div className={styles.portfolioCard}>
              <img className={styles.portfolioImage} src="https://images.unsplash.com/photo-1625842268584-8f3296236761?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80" alt="" />
              <div className={styles.portfolioContent}>
                <h4 className={styles.portfolioTitle}>Together</h4>
                <p className={styles.portfolioDescription}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti illo earum reprehenderit voluptatem nulla quae voluptates, blanditiis cum? Quidem praesentium, dolores velit animi quod cumque dignissimos sed sapiente at eius.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

const headTextAnimation = {
  initial: { x: 100, opacity: 0 },
  animate: { x: 0, opacity: 1 },
  transition: {
    type: "spring",
    damping: 5,
    stiffness: 40,
    restDelta: 0.001,
    duration: 0.3,
  },
};

const headContentAnimation = {
  initial: { y: 100, opacity: 0 },
  animate: { y: 0, opacity: 1 },
  transition: {
    type: "spring",
    damping: 7,
    stiffness: 30,
    restDelta: 0.001,
    duration: 0.6,
    delay: 0.2,
    delayChildren: 0.2,
  },
};

const headImageAnimation = {
  initial: { x: 100, opacity: 0 },
  animate: { x: 0, opacity: 1 },
  transition: {
    type: "spring",
    damping: 5,
    stiffness: 40,
    restDelta: 0.001,
    duration: 0.3,
  },
};
