import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { motion } from "framer-motion";
import { FaTwitter, FaGithub, FaBook, FaRegSmileBeam } from "react-icons/fa";
import { SiZenn } from "react-icons/si";
import { GiHumanEar } from "react-icons/gi";

import { Archivo_Black } from "next/font/google";

const archivoBlack = Archivo_Black({
  weight: "400",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.home}>
        {/* Introduce */}
        <div className={`section ${styles.main}`}>
          <div>
            <motion.div {...headTextAnimation}>
              <h1 className={`${archivoBlack.className} ${styles.name}`}>
                Airi Narita
              </h1>
            </motion.div>
            <motion.div {...headContentAnimation}>
              <h2 className={styles.title}>~Nothing impossible!!!~</h2>
              <p className={styles.description}>
                学習の中で、今まで継続していることとして
                <br />
                自分の知識定着や、周りの学習者のためにも学んだことを
                <br />
                毎日アウトプットを行なっています。
                <br />
                <strong>&quot;アウトプットこそ最大の学び &quot;</strong>
                <br />
                ぜひ以下のリンクからご覧ください！
              </p>
            </motion.div>
            <motion.div {...headContentAnimation} className={styles.sns}>
              <motion.div
                whileHover={{ scale: 1.1 }}
                whileTap={{ scale: 0.9 }}
                className={styles.snsItem}
              >
                <a href="https://twitter.com/aaaairinkiyowo" target="_blank">
                  <FaTwitter size={"1.6rem"} />
                </a>
              </motion.div>
              <motion.div
                whileHover={{ scale: 1.1 }}
                whileTap={{ scale: 0.9 }}
                className={styles.snsItem}
              >
                <a href="https://github.com/airinarita" target="_blank">
                  <FaGithub size={"1.6rem"}></FaGithub>
                </a>
              </motion.div>
              <motion.div
                whileHover={{ scale: 1.1 }}
                whileTap={{ scale: 0.9 }}
                className={styles.snsItem}
              >
                <a href="https://zenn.dev/airiswim" target="_blank">
                  <SiZenn size={"1.6rem"} />
                </a>
              </motion.div>
            </motion.div>
          </div>
          <motion.div {...headImageAnimation}>
            <div className={styles.selfImage}>
              <img className={styles.selfImage} src="/airi.jpg" />
            </div>
          </motion.div>
        </div>
        {/* P */}
        <div className={`section ${styles.personal}`}>
          <h2 className="sectionTitle">Personal</h2>
          <motion.div
            variants={container}
            initial="hidden"
            animate="show"
            className={styles.personalInner}
          >
            <motion.div variants={item} className={styles.personalCard}>
              <motion.div
                whileHover={{ scale: 1.4 }}
                whileTap={{ scale: 0.9 }}
                className={styles.personalIcon}
              >
                <GiHumanEar size={"3rem"} />
              </motion.div>
              <p>
                Lorem ipsum, dolor sit amet consectetur adipisicing elit.
                Necessitatibus nobis voluptas dolorem, ut odit fuga sapiente
                tenetur, corporis nam itaque laborum doloribus debitis
                voluptatem nesciunt recusandae accusamus voluptates maxime?
                Obcaecati? Lorem ipsum, dolor sit amet consectetur adipisicing
                elit. Necessitatibus nobis voluptas dolorem, ut odit fuga
                sapiente tenetur, corporis nam itaque laborum doloribus debitis
                voluptatem nesciunt recusandae accusamus voluptates maxime?
                Obcaecati? Lorem ipsum, dolor sit amet consectetur adipisicing
                elit. Necessitatibus nobis voluptas dolorem, ut odit fuga
                sapiente tenetur, corporis nam itaque laborum doloribus debitis
                voluptatem nesciunt recusandae accusamus voluptates maxime?
                Obcaecati?
              </p>
            </motion.div>
            <motion.div variants={item} className={styles.personalCard}>
              <motion.div
                whileHover={{ scale: 1.4 }}
                whileTap={{ scale: 0.9 }}
                className={styles.personalIcon}
              >
                <FaBook size={"3rem"} />
              </motion.div>
              <p>
                Lorem ipsum, dolor sit amet consectetur adipisicing elit.
                Necessitatibus nobis voluptas dolorem, ut odit fuga sapiente
                tenetur, corporis nam itaque laborum doloribus debitis
                voluptatem nesciunt recusandae accusamus voluptates maxime?
                Obcaecati? Lorem ipsum, dolor sit amet consectetur adipisicing
                elit. Necessitatibus nobis voluptas dolorem, ut odit fuga
                sapiente tenetur, corporis nam itaque laborum doloribus debitis
                voluptatem nesciunt recusandae accusamus voluptates maxime?
                Obcaecati? Lorem ipsum, dolor sit amet consectetur adipisicing
                elit. Necessitatibus nobis voluptas dolorem, ut odit fuga
                sapiente tenetur, corporis nam itaque laborum doloribus debitis
                voluptatem nesciunt recusandae accusamus voluptates maxime?
                Obcaecati?
              </p>
            </motion.div>
            <motion.div variants={item} className={styles.personalCard}>
              <motion.div
                whileHover={{ scale: 1.4 }}
                whileTap={{ scale: 0.9 }}
                className={styles.personalIcon}
              >
                <FaRegSmileBeam size={"3rem"} />
              </motion.div>
              <p>
                Lorem ipsum, dolor sit amet consectetur adipisicing elit.
                Necessitatibus nobis voluptas dolorem, ut odit fuga sapiente
                tenetur, corporis nam itaque laborum doloribus debitis
                voluptatem nesciunt recusandae accusamus voluptates maxime?
                Obcaecati? Lorem ipsum, dolor sit amet consectetur adipisicing
                elit. Necessitatibus nobis voluptas dolorem, ut odit fuga
                sapiente tenetur, corporis nam itaque laborum doloribus debitis
                voluptatem nesciunt recusandae accusamus voluptates maxime?
                Obcaecati? Lorem ipsum, dolor sit amet consectetur adipisicing
                elit. Necessitatibus nobis voluptas dolorem, ut odit fuga
                sapiente tenetur, corporis nam itaque laborum doloribus debitis
                voluptatem nesciunt recusandae accusamus voluptates maxime?
                Obcaecati?
              </p>
            </motion.div>
          </motion.div>
        </div>
        {/* S */}
        <div className={`section ${styles.skill}`}>
          <h2 className="sectionTitle">Skill</h2>
          <motion.div
            variants={container}
            initial="hidden"
            animate="show"
            className={styles.skillInner}
          >
            <motion.div variants={item} className={styles.skillCard}>
              <motion.div
                whileHover={{ scale: 1.4 }}
                whileTap={{ scale: 1 }}
                className={styles.skillIcon}
              >
                <h4 className={`${archivoBlack.className} ${styles.skillCardTitle}`}>BACKEND</h4>
              </motion.div>
              <p>
                Lorem ipsum, dolor sit amet consectetur adipisicing elit.
                Necessitatibus nobis voluptas dolorem, ut odit fuga sapiente
                tenetur, corporis nam itaque laborum doloribus debitis
                voluptatem nesciunt recusandae accusamus voluptates maxime?
                Obcaecati? Lorem ipsum, dolor sit amet consectetur adipisicing
                elit. Necessitatibus nobis voluptas dolorem, ut odit fuga
                sapiente tenetur, corporis nam itaque laborum doloribus debitis
                voluptatem nesciunt recusandae accusamus voluptates maxime?
                Obcaecati? Lorem ipsum, dolor sit amet consectetur adipisicing
                elit. Necessitatibus nobis voluptas dolorem, ut odit fuga
                sapiente tenetur, corporis nam itaque laborum doloribus debitis
                voluptatem nesciunt recusandae accusamus voluptates maxime?
                Obcaecati?
              </p>
            </motion.div>
            <motion.div variants={item} className={styles.skillCard}>
              <motion.div
                whileHover={{ scale: 1.4 }}
                whileTap={{ scale: 1 }}
                className={styles.skillIcon}
              >
                 <h4 className={`${archivoBlack.className} ${styles.skillCardTitle}`}>FRONTEND</h4>
              </motion.div>
              <p>
                Lorem ipsum, dolor sit amet consectetur adipisicing elit.
                Necessitatibus nobis voluptas dolorem, ut odit fuga sapiente
                tenetur, corporis nam itaque laborum doloribus debitis
                voluptatem nesciunt recusandae accusamus voluptates maxime?
                Obcaecati? Lorem ipsum, dolor sit amet consectetur adipisicing
                elit. Necessitatibus nobis voluptas dolorem, ut odit fuga
                sapiente tenetur, corporis nam itaque laborum doloribus debitis
                voluptatem nesciunt recusandae accusamus voluptates maxime?
                Obcaecati? Lorem ipsum, dolor sit amet consectetur adipisicing
                elit. Necessitatibus nobis voluptas dolorem, ut odit fuga
                sapiente tenetur, corporis nam itaque laborum doloribus debitis
                voluptatem nesciunt recusandae accusamus voluptates maxime?
                Obcaecati?
              </p>
            </motion.div>
            <motion.div variants={item} className={styles.skillCard}>
              <motion.div
                whileHover={{ scale: 1.4 }}
                whileTap={{ scale: 1 }}
                className={styles.skillIcon}
              >
                 <h4 className={`${archivoBlack.className} ${styles.skillCardTitle}`}>INFRA</h4>
              </motion.div>
              <p>
                Lorem ipsum, dolor sit amet consectetur adipisicing elit.
                Necessitatibus nobis voluptas dolorem, ut odit fuga sapiente
                tenetur, corporis nam itaque laborum doloribus debitis
                voluptatem nesciunt recusandae accusamus voluptates maxime?
                Obcaecati? Lorem ipsum, dolor sit amet consectetur adipisicing
                elit. Necessitatibus nobis voluptas dolorem, ut odit fuga
                sapiente tenetur, corporis nam itaque laborum doloribus debitis
                voluptatem nesciunt recusandae accusamus voluptates maxime?
                Obcaecati? Lorem ipsum, dolor sit amet consectetur adipisicing
                elit. Necessitatibus nobis voluptas dolorem, ut odit fuga
                sapiente tenetur, corporis nam itaque laborum doloribus debitis
                voluptatem nesciunt recusandae accusamus voluptates maxime?
                Obcaecati?
              </p>
            </motion.div>
          </motion.div>
        </div>
        {/* Slider */}
        <div className={`section ${styles.slider}`}>
          <div className={styles.sliderInner}>
            <div className={styles.sliderItem}>
              <img className={styles.sliderItem} src="/pc.png" />
            </div>
            <div className={styles.sliderItem}>
              <img className={styles.sliderItem} src="/daigaku.jpg" />
            </div>
            <div className={styles.sliderItem}>
              <img className={styles.sliderItem} src="/ww.jpg" />
            </div>
            <div className={styles.sliderItem}>
              <img className={styles.sliderItem} src="/study.jpg" />
            </div>
            <div className={styles.sliderItem}>
              <img className={styles.sliderItem} src="/aws.jpg" />
            </div>
            <div className={styles.sliderItem}>
              <img className={styles.sliderItem} src="/fes.jpg" />
            </div>
            <div className={styles.sliderItem}>
              <img className={styles.sliderItem} src="/dmm.png" />
            </div>
            <div className={styles.sliderItem}>
              <img className={styles.sliderItem} src="/image.jpg" />
            </div>
          </div>
        </div>
        {/* Portfolio */}
        <div className={`section ${styles.portfolio}`}>
          <h2 className="sectionTitle">Portfolio</h2>
          <div className={styles.portfolioInner}>
            <div className={styles.portfolioCard}>
              <img className={styles.portfolioImage} src="/together.png" />
              <div className={styles.portfolioContent}>
                <h4 className={styles.portfolioTitle}>
                  <a href="https://narita-airi.com/" target="_blank">
                    Together
                  </a>
                </h4>
                <p className={styles.portfolioDescription}>
                  <strong>技術ブログ＆学習イベント投稿サイト</strong>
                  <br />
                  <strong>
                    &quot;If You Want To Go Far, Go Together&quot;
                    (遠くへ行きたいならみんなで行け)
                  </strong>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

const headTextAnimation = {
  initial: { x: 100, opacity: 0 },
  animate: { x: 0, opacity: 1 },
  transition: {
    type: "spring",
    damping: 5,
    stiffness: 40,
    restDelta: 0.001,
    duration: 0.3,
  },
};

const headContentAnimation = {
  initial: { y: 100, opacity: 0 },
  animate: { y: 0, opacity: 1 },
  transition: {
    type: "spring",
    damping: 7,
    stiffness: 30,
    restDelta: 0.001,
    duration: 0.6,
    delay: 0.2,
    delayChildren: 0.2,
  },
};

const headImageAnimation = {
  initial: { x: 100, opacity: 0 },
  animate: { x: 0, opacity: 1 },
  transition: {
    type: "spring",
    damping: 5,
    stiffness: 40,
    restDelta: 0.001,
    duration: 0.3,
  },
};

const container = {
  hidden: { opacity: 0 },
  show: {
    opacity: 1,
    transition: {
      delayChildren: 0.5,
    },
  },
};

const item = {
  hidden: { opacity: 0 },
  show: { opacity: 1 },
};
